#!/usr/bin/env ruby

require "fileutils"
require "json"
require "rubygems"
require "tempfile"
require "yaml"

require "active_support/inflector"
require "lz4-ruby"

require_relative "unity_bundle"
require_relative "assets"

MANAGED_ASSEMBLY="#{Dir.home}/.local/share/Steam/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Managed/Assembly-CSharp.dll"
LANGUAGE_CN_ASSET_BUNDLE="#{Dir.home}/.local/share/Steam/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/GameResources/language_cn.uab"
OUTPUT_DIR="zh-hans"

class Lz4Uncompress
  def initialize(uncompressed_size)
    @uncompressed_size = uncompressed_size
  end

  def decode(compressed)
    return compressed if compressed.bytesize == @uncompressed_size

    uncompressed = LZ4::Raw::decompress(compressed, @uncompressed_size).first
    raise StandardError, "expected #{@uncompressed_size} bytes, got #{uncompressed.length} bytes" if @uncompressed_size != uncompressed.length

    uncompressed
  end
end

def enum_to_string(type)
  type.class_id.to_s.gsub(/\Aclass_id_unity_(.+)_[0-9a-f]{32}_\d+\z/, '\1').camelize
end

ub = UnityBundle.from_file(LANGUAGE_CN_ASSET_BUNDLE)
ub_data = ub.blocks.map(&:data).join

FileUtils.mkdir_p(OUTPUT_DIR)
ub.block_info_and_directory.data.directory_info.each do |ub_info|
  # a_name = ub_info.path
  # puts "[+] update #{a_name}..."

  a_data = ub_data[ub_info.offset, ub_info.size]
  a_path = Tempfile.new
  File.binwrite(a_path, a_data)
  a = Assets.from_file(a_path)

  a.metadata.objects.data.each do |object|
    type = enum_to_string(object)
    next unless type == "TextAsset"

    data = object.data

    name = data.m_name.data
    text = data.m_script.data
    lines = text.split("\n")

    abort "not a language file: #{name}" unless name.end_with?("_language")

    puts "  [+] saving #{name}..."
    if name == "ui_language"
      keys_yaml = `
        ilspycmd -t LanguageKey '#{MANAGED_ASSEMBLY}' \
          | awk '/private static readonly Dictionary<string, ushort> _filedIdMap = new Dictionary<string, ushort>/,/};/' \
          | grep -E '\\{[^}]+\\}' -o | sed -E 's/^\\{ "([^"]+)", ([0-9]+) \\}$/\\1: \\2/g'
      `
      keys = YAML.safe_load(keys_yaml)
      entries = keys.transform_values { |id| lines[id] }
      next File.write(File.join(OUTPUT_DIR, "#{name}.json"), JSON.pretty_generate(entries))
    end

    File.binwrite(File.join(OUTPUT_DIR, "#{name}.txt"), text)
  end
end
